service:
  name: sample-serverless-api

# plugins:
#   - serverless-python-requirements
#   - serverless-offline-python

provider:
  name: aws
  region: ap-northeast-1
  stage: dev
  runtime: python3.8
  stackName: sample-serverless-api
  apiName: sample-serverless-api
  environment:
    DEFAULT_DATA_LIMIT: 20
    ENV: dev

functions:
  listPromotionalItems:
    name: list_promotional_items
    handler: src/handlers/list_promotional_items.handler
    events:
      - http:
          path: /promotional_items
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                limit: false

custom:
  pythonRequirements:
    usePipenv: true

package:
  exclude:
    - .git/**
    - .venv/**
    - .vscode/**
    - tests
    - .serverless/**
    - sample
    - README.md
